apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-tmt
  labels:
    app: auth-service-tmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-tmt
  template:
    metadata:
      labels:
        app: auth-service-tmt
    spec:
      containers:
        - name: auth-service-tmt
          image: aftechsolution/auth-service:33
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  ports:
    - targetPort: 5004
      protocol: TCP
      port: 80
  selector:
    app: auth-service-tmt
