apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-tmt
  labels:
    app: cloud-gateway-tmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway-tmt
  template:
    metadata:
      labels:
        app: cloud-gateway-tmt
    spec:
      containers:
        - name: cloud-gateway-tmt
          image: aftechsolution/cloud-gateway:20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: cloud-gateway-tmt
