apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service-tmt
  labels:
    app:  project-service-tmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  project-service-tmt
  template:
    metadata:
      labels:
        app:  project-service-tmt
    spec:
      containers:
        - name:  project-service-tmt
          image: aftechsolution/project-service:44
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name:  project-service-svc
spec:
  ports:
    - targetPort: 5003
      protocol: TCP
      port: 80
  selector:
    app: project-service-tmt
