apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-details-service-tmt
  labels:
    app:  user-details-service-tmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  user-details-service-tmt
  template:
    metadata:
      labels:
        app:  user-details-service-tmt
    spec:
      containers:
        - name:  user-details-service-tmt
          image: aftechsolution/user-details-service:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5005

---
apiVersion: v1
kind: Service
metadata:
  name:  user-details-service-svc
spec:
  ports:
    - targetPort: 5005
      protocol: TCP
      port: 80
  selector:
    app: user-details-service-tmt
