apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-web-tmt
  labels:
    app: angular-web-tmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-web-tmt
  template:
    metadata:
      labels:
        app: angular-web-tmt
    spec:
      containers:
        - name: angular-web-tmt
          image: aftechsolution/web-angular:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: angular-web-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: angular-web-tmt
